# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rrReml <- function(y, gen, maxit = 500L, tol = 10e-6) {
    .Call('_SoyNAMSelectionMethods_rrReml', PACKAGE = 'SoyNAMSelectionMethods', y, gen, maxit, tol)
}

